EfacilCursos_Homologacao/Models/AcessoModel.cs
using System.ComponentModel.DataAnnotations;

namespace EfacilCursos_Homologacao.Models
{
    public class AcessoModel
    {
        [Required]
        public string Email { get; set; }

        [Required]
        public string Senha { get; set; }
    }
}

EfacilCursos_Homologacao/Models/AlunoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EfacilCursos_Homologacao.Models
{
    public class AlunoModel
    {
        [Key]
        public Guid Id_Aluno { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "Tamanho máximo de Nome é 100 caracteres")]
        public string Nome { get; set; }

        [Required]
        [StringLength(320, ErrorMessage = "Tamanho máximo de Email é 320 caracteres")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "Tamanho máximo de Senha é 100 caracteres")]
        public string Senha { get; set; }

        [Required]
        [StringLength(11, ErrorMessage = "Tamanho máximo de CPF é 11 caracteres")]
        public string CPF { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "Tamanho máximo de Estado é 100 caracteres")]
        public string Estado { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "Tamanho máximo de Telefone é 100 caracteres")]
        public string Telefone { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "Tamanho máximo de Endereço é 100 caracteres")]
        public string Endereco { get; set; }

        [Required]
        [StringLength(18, ErrorMessage = "Tamanho máximo de CEP é 18 caracteres")]
        public string Cep { get; set; }

        [Required]
        [StringLength(18, ErrorMessage = "Tamanho máximo de Sexo é 18 caracteres")]
        public string Sexo { get; set; }

        [Required]
        [StringLength(600, ErrorMessage = "Tamanho máximo de Url é 600 caracteres")]
       
        public DateTime DataCadastro { get; set; }
        public DateTime DataNascimento { get; set; }
        public bool Ativo { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            return Enumerable.Empty<ValidationResult>();
        }
    }
}

EfacilCursos_Homologacao/Models/ErrorViewModel.cs
using System;

namespace EfacilCursos_Homologacao.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EfacilCursos_Homologacao/Controllers/AcessoController.cs
using EfacilCursos_Homologacao.Data;
using EfacilCursos_Homologacao.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace EfacilCursos_Homologacao.Controllers
{
    public class AcessoController : Controller
    {
        IHostingEnvironment _appEnvironment;

        private AppDbContext _Context;

        public AcessoController(AppDbContext context, IHostingEnvironment env)
        {
            _Context = context;
            _appEnvironment = env;
        }

        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Entrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(AcessoModel model)
        {

            var usuario = _Context.Usuarios.FirstOrDefault(c => c.Email == model.Email && c.Senha == model.Senha);

            if (usuario == null)
            {
                ViewBag.Messagen = "Usúario ou senha invalido.";
                return View(model);
            }

            return RedirectToAction("Index");

        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Entrar");
        }
    }
}

EfacilCursos_Homologacao/Controllers/AlunoController.cs
using EfacilCursos_Homologacao.Data;
using EfacilCursos_Homologacao.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace EfacilCursos_Homologacao.Controllers
{
    public class AlunoController : Controller
    {
        IHostingEnvironment _appEnvironment;

        private AppDbContext _Context;

        public AlunoController(AppDbContext context, IHostingEnvironment env)
        {
            _Context = context;
            _appEnvironment = env;
        }       

        public ActionResult Usuario()
        {
            return View();
        }

        public ActionResult AlunoAdd(int? id)
        {
            return View(new AlunoModel());
        }

        
        public IActionResult UsuarioGrid(string search)
        {
            return PartialView(string.IsNullOrWhiteSpace(search) ? _Context.Usuarios.AsQueryable() : _Context.Usuarios.Where(c =>
                c.Nome.Contains(search) ||
                c.Email.Contains(search)));
        }
               
        public ActionResult UsuarioEdit(int? id)
        {
            if (id > 0)
            {
                return View(_Context.Usuarios.Find(id));
            }
            else
            {
                return View(new AlunoModel());
            }
        }
               
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UsuarioEdit(AlunoModel Aluno)
        {
            try
            {               
                var validacao = _Context.Usuarios.FirstOrDefault(c => c.Email == Aluno.Email);

                if (validacao != null)
                {
                    ViewBag.Messagen = "Não foi possivel cadastrar Email, já é cadastrado na nossa base";
                    return RedirectToAction("HomeCursos");
                }
                else
                {
                    Aluno.Ativo = true;
                    Aluno.DataCadastro = DateTime.Now;                  

                    _Context.Usuarios.Add(Aluno);
                    _Context.SaveChanges();
                }
                return RedirectToAction("HomeCursos");
               
            }
            catch (Exception)
            {
                return View(Aluno);
            }
        }
    }
}

EfacilCursos_Homologacao/Controllers/HomeController.cs
using EfacilCursos_Homologacao.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EfacilCursos_Homologacao.Controllers
{

    [Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }

}

EfacilCursos_Homologacao/Views/Acesso/Login.cshtml
@model EfacilCursos_Homologacao.Models.AcessoModel

@{
    ViewData["Title"] = "Login";
}

<h2>Login</h2>

<h4>AcessoModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Senha" class="control-label"></label>
                <input asp-for="Senha" class="form-control" />
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EfacilCursos_Homologacao/Views/Aluno/AlunoAdd.cshtml
@model EfacilCursos_Homologacao.Models.AlunoModel

@{
    ViewData["Title"] = "AlunoAdd";
}

<h2>AlunoAdd</h2>

<h4>AlunoModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AlunoAdd">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id_Aluno" class="control-label"></label>
                <input asp-for="Id_Aluno" class="form-control" />
                <span asp-validation-for="Id_Aluno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Senha" class="control-label"></label>
                <input asp-for="Senha" class="form-control" />
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco" class="control-label"></label>
                <input asp-for="Endereco" class="form-control" />
                <span asp-validation-for="Endereco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cep" class="control-label"></label>
                <input asp-for="Cep" class="form-control" />
                <span asp-validation-for="Cep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <input asp-for="Sexo" class="form-control" />
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataCadastro" class="control-label"></label>
                <input asp-for="DataCadastro" class="form-control" />
                <span asp-validation-for="DataCadastro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

EfacilCursos_Homologacao/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

EfacilCursos_Homologacao/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EfacilCursos_Homologacao/Views/Shared/_LayoutHome.cshtml
@model EfacilCursos_Homologacao.Models.AcessoModel
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="~/images/icons/favicon.ico" />
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/vendor/bootstrap/css/bootstrap.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/css/util.css">
	<link rel="stylesheet" type="text/css" href="~/css/main.css">
	<!--===============================================================================================-->
</head>
<body>
	<div class="container">
		<form asp-action="Index">
			@Html.Hidden("returnUrl", ViewBag.returnUrl as string)
			@if (ViewBag.Messagen != null)
			{
				<p class="text-danger">@ViewBag.Messagen</p>
			}
		</form>
	</div>
	@RenderBody()
<div class="limiter">
	@Html.Hidden("returnUrl", ViewBag.returnUrl as string)
	@if (ViewBag.Messagen != null)
	{
		<p class="text-danger">@ViewBag.Messagen</p>
	}
	<div class="container-login100">
		<div class="wrap-login100">
			<div class="login100-pic js-tilt" data-tilt>
				<img src="~/images/img-01.png" alt="IMG">
			</div>
			<form class="login100-form validate-form">
				<span class="login100-form-title">
					Efacil Cursos
				</span>
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
					<input asp-for="Email" type="text" class="input100" name="email" placeholder="Email" />
					<span asp-validation-for="Email" class="focus-input100"></span>
					<span class="symbol-input100">
						<i class="fa fa-envelope" aria-hidden="true"></i>
					</span>
				</div>
				<div class="wrap-input100 validate-input" data-validate="Password is required">
					<input asp-for="Senha" type="password" class="input100" name="pass" placeholder="Senha" />
					<span asp-validation-for="Senha" class="focus-input100"></span>
					<span class="symbol-input100">
						<i class="fa fa-lock" aria-hidden="true"></i>
					</span>
				</div>
				<div class="container-login100-form-btn">
					@*<input type="submit" value="Entrar" class="login100-form-btn" />*@
					<input type="button" value="Entrar" class="login100-form-btn" onclick="@("window.location.href='" + @Url.Action("HomeCursos", "Acesso") + "'");" />
				</div>
				<div class="text-center p-t-12">
					<span class="txt1">
						@*Forgot*@
					</span>
					<a class="txt2" href="#">
						@*Username / Password?*@
					</a>
				</div>
				<div class="text-center p-t-90">
					<a class="txt2" asp-action="SelecionaTipoCadastroUsuario" >
						Criar nova Conta
						<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
					</a>
				</div>
			</form>
		</div>
	</div>
</div>
	<!--===============================================================================================-->
	<script src="~/vendor/jquery/jquery-3.2.1.min.js"></script>
	<!--===============================================================================================-->
	<script src="~/vendor/bootstrap/js/popper.js"></script>
	<script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
	<!--===============================================================================================-->
	<script src="~/vendor/select2/select2.min.js"></script>
	<!--===============================================================================================-->
	<script src="~/vendor/tilt/tilt.jquery.min.js"></script>
	<script>
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
	<!--===============================================================================================-->
	<script src="~/js/main.js"></script>
</body>
</html>

EfacilCursos_Homologacao/Views/Shared/_LayoutProfessorAdicionaNovoCurso.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>@ViewData["Title"] | Efacil Cursos</title>
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
	<link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css">
	<link rel="stylesheet" href="~/admin-lte/css/AdminLTE.min.css">
	<link rel="stylesheet" href="~/admin-lte/css/skins/skin-blue.min.css">
	<link rel="stylesheet"
		  href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

	<script src="https://kit.fontawesome.com/008a52c14b.js" crossorigin="anonymous"></script>
</head>
<body class="hold-transition skin-blue sidebar-mini">
	<div class="wrapper">

		<!-- Main Header -->
		<header class="main-header">

			<!-- Logo -->
			<a href="index2.html" class="logo">
				<!-- mini logo for sidebar mini 50x50 pixels -->
				<span class="logo-mini"><b>E</b>FC</span>
				<!-- logo for regular state and mobile devices -->
				<span class="logo-lg"><b>Efacil</b>Cursos</span>
			</a>

			<!-- Header Navbar -->
			<nav class="navbar navbar-static-top" role="navigation">
				<!-- Sidebar toggle button-->
				<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
					<span class="sr-only">Toggle navigation</span>
				</a>
			</nav>
		</header>
		<!-- Left side column. contains the logo and sidebar -->
		<aside class="main-sidebar">

			<!-- sidebar: style can be found in sidebar.less -->
			<section class="sidebar">

				<!-- Sidebar user panel (optional) -->
				<div class="user-panel">
					<div class="pull-left image">
						<img src="~/admin-lte/img/user2-160x160.jpg" class="img-circle" alt="User Image">
					</div>
					<div class="pull-left info">
						<p>Nathan Soares</p>
						<!-- Status -->
						<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
					</div>
				</div>
				<!-- search form (Optional) -->
				<form action="#" method="get" class="sidebar-form">
					<div class="input-group">
						<input type="text" name="q" class="form-control" placeholder="Pesquisar...">
						<span class="input-group-btn">
							<button type="submit" name="search" id="search-btn" class="btn btn-flat">
								<i class="fa fa-search"></i>
							</button>
						</span>
					</div>
				</form>
				<!-- /.search form -->
				<!-- Sidebar Menu -->
				<ul class="sidebar-menu" data-widget="tree">
					<li class="header">ACESSO RÁPIDO - PROFESSOR</li>
					<!-- Optionally, you can add icons to the links -->
					<li class="active"><a href="#"><i class="fa fa-link"></i> <span>Perfil</span></a></li>
					<li class="treeview">
						<a href="#">
							<i class="fa fa-link"></i> <span>Cursos</span>
							<span class="pull-right-container">
								<i class="fa fa-angle-left pull-right"></i>
							</span>
						</a>
						<ul class="treeview-menu">
							<li>@Html.ActionLink("Todos os Cursos", "HomeCursos", "Acesso")</li>
							<li>@Html.ActionLink("Adicionar novo Curso", "ProfessorAdicionaNovoCurso", "Acesso")</li>
						</ul>
					</li>
				</ul>
				<!-- /.sidebar-menu -->
			</section>
			<!-- /.sidebar -->
		</aside>
		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<section class="content-header">
				<h1>
					@*Page Header
						<small>Optional description</small>*@
				</h1>
			</section>
			<!-- Main content -->
			<section class="content container-fluid">
				@RenderBody()
			</section>
			<!-- /.content -->
		</div>
		<!-- /.content-wrapper -->
		<!-- Main Footer -->
		@*<footer class="main-footer">

				<div class="pull-right hidden-xs">
					Efacil Cursos
				</div>

				<span>Copyright © Efacil @DateTime.Now.Year</span>
			</footer>*@
		<!-- Control Sidebar -->
		<aside class="control-sidebar control-sidebar-dark">
			<!-- Create the tabs -->
			<ul class="nav nav-tabs nav-justified control-sidebar-tabs">
				<li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
				<li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
			</ul>
			<!-- Tab panes -->
			<div class="tab-content">
				<!-- Home tab content -->
				<div class="tab-pane active" id="control-sidebar-home-tab">
					<h3 class="control-sidebar-heading">Recent Activity</h3>
					<ul class="control-sidebar-menu">
						<li>
							<a href="javascript:;">
								<i class="menu-icon fa fa-birthday-cake bg-red"></i>

								<div class="menu-info">
									<h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

									<p>Will be 23 on April 24th</p>
								</div>
							</a>
						</li>
					</ul>
					<!-- /.control-sidebar-menu -->
					<h3 class="control-sidebar-heading">Tasks Progress</h3>
					<ul class="control-sidebar-menu">
						<li>
							<a href="javascript:;">
								<h4 class="control-sidebar-subheading">
									Custom Template Design
									<span class="pull-right-container">
										<span class="label label-danger pull-right">70%</span>
									</span>
								</h4>

								<div class="progress progress-xxs">
									<div class="progress-bar progress-bar-danger" style="width: 70%"></div>
								</div>
							</a>
						</li>
					</ul>
					<!-- /.control-sidebar-menu -->
				</div>
				<!-- /.tab-pane -->
				<!-- Stats tab content -->
				<div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
				<!-- /.tab-pane -->
				<!-- Settings tab content -->
				<div class="tab-pane" id="control-sidebar-settings-tab">
					<form method="post">
						<h3 class="control-sidebar-heading">General Settings</h3>

						<div class="form-group">
							<label class="control-sidebar-subheading">
								Report panel usage
								<input type="checkbox" class="pull-right" checked>
							</label>
							<p>
								Some information about this general settings option
							</p>
						</div>
						<!-- /.form-group -->
					</form>
				</div>
				<!-- /.tab-pane -->
			</div>
		</aside>
		<!-- /.control-sidebar -->
		<!-- Add the sidebar's background. This div must be placed
		immediately after the control sidebar -->
		<div class="control-sidebar-bg"></div>
	</div>
	<!-- ./wrapper -->
	<!-- REQUIRED JS SCRIPTS -->
	<!-- jQuery 3 -->
	<script src="~/lib/jquery/jquery.min.js"></script>
	<!-- Bootstrap 3.3.7 -->
	<script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
	<!-- AdminLTE App -->
	<script src="~/admin-lte/js/adminlte.min.js"></script>

	<!-- Optionally, you can add Slimscroll and FastClick plugins.
		 Both of these plugins are recommended to enhance the
		 user experience. -->

	@RenderSection("Scripts", required: false)
</body>
</html>

EfacilCursos_Homologacao/Views/Shared/_LayoutTipoCadastroUsuario.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;700&display=swap"
		  rel="stylesheet" />
	<link rel="stylesheet" href="~/cssSelecionaTipoUsuario/StyleSelecionaTipoUsuario.css" />
	<script src="https://kit.fontawesome.com/008a52c14b.js"
			crossorigin="anonymous"></script>
	<title>EFacil Cursos | Tipo de Usuário</title>
</head>
<body>
	@RenderBody()
	<div class="container-login">
		<header class="page-header">
			<a href="@Url.Action("index", "Acesso")"><h1>Efacil Cursos</h1></a>
			<a href="@Url.Action("index", "Acesso")">
				<div class="circle-icon">
					<i class="fas fa-arrow-left"></i>
				</div>
			</a>
		</header>
		<div class="main-content">
			<h1 class="role-question">
				O que você será?...
			</h1>
			<div class="cards-container">
				<div class="card-and-pop-up">
					<div class="card" id="student-card">
						<div class="label"><p>Aluno</p></div>
						<div class="card-main-content">
							<i class="fas fa-user"></i>
						</div>
					</div>
					<i class="far fa-question-circle question-mark"></i>
					<div class="pop-up">
						Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam
						quisquam obcaecati voluptatibus soluta consequatur, incidunt
						eveniet dicta. Culpa sint porro eligendi beatae, excepturi officia
						facilis sit voluptate libero at error!
					</div>
				</div>
				<div class="card-and-pop-up">
					<div class="card" id="teacher-card">
						<div class="label"><p>Professor</p></div>
						<div class="card-main-content">
							<i class="fas fa-user-tie"></i>
						</div>
					</div>
					<i class="far fa-question-circle question-mark"></i>
					<div class="pop-up">
						Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam
						quisquam obcaecati voluptatibus soluta consequatur, incidunt
						eveniet dicta. Culpa sint porro eligendi beatae, excepturi officia
						facilis sit voluptate libero at error!
					</div>
				</div>
			</div>
			<button disabled class="register-btn">
				@*Cadastrar-se
				<div class="circle-icon">
					<i class="fas fa-arrow-right"></i>
				</div>*@
			</button>
		</div>
	</div>
	<script src="~/jsSelecionaTipoUsuario/ScriptSelecionaTipoUsuario.js"></script>
</body>
</html>

EfacilCursos_Homologacao/Views/Shared/_Nav.cshtml
<header class="navbar-wrapper">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="row">

                <div class="navbar-header col-lg-5 col-sm-5">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navBar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    <a asp-controller="Home" asp-action="Index"><img class="navbar-logo" src="~/images/logotipoconstrutora5.png" alt="Logo Construtora" /></a>
                </div>

                <div id="navBar" class="navbar-collapse collapse col-lg-4 col-sm-4">
                    <ul class="nav navbar-nav">
                        <li><a class="page-scroll" href="/#quem">Quem Somos</a></li>
                        <li><a class="page-scroll" href="/#informacoes">Plantas Baixa</a></li>
                        <li><a class="page-scroll" href="/#servicos">Serviços</a></li>
                        <li><a class="page-scroll" href="/#contato">Contato</a></li>
                    </ul>
                    </div>

                <div class="navbar-login col-lg-2 col-sm-2">
                    <div class="navbar-form" style="border-top: none; border-bottom: none;">
                        <a asp-area="" asp-controller="Acesso" asp-action="Entrar" class="btn btn-default">
                            <span class="glyphicon glyphicon-user primary"></span>
                            <span class="hidden-xs entrar">Área Administrativa</span>
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </nav>
</header>